### ISSUE TITLE
hipache not listening on port 80

### ISSUE THREAD

**Issue by zackbraksa** [hipache/hipache#162]
I installed hipache using the instructions on the README. 

When I run it, it fires up successfully, doesn't give any errors of any kind, but it just doesn't work when I do something like `curl localhost`, also doing `netstat -l` doesn't show it listening on port 80 or http. 

What's even weird is that it's listening on some random port, and the port get regenerated every time I stop it and run it again. 

Any idea why ? and how to fix it ?

**Comment by alibby** [comment]
Looks fixed to me, thanks!

**Comment by jzorn** [comment]
If you are on a recent (>=  2.6.26) Kernel, try [Capabilities](http://man7.org/linux/man-pages/man7/capabilities.7.html):

```bash
setcap 'cap_net_bind_service=+ep' /usr/local/bin/hipache
```

**Comment by prologic** [comment]
So this is weird; I'm getting this *exact* issue trying to run:

```#!bash
docker run -i -t --rm -p 80:80 hipache:0.2.8
```

The *reason* I'm using the ``0.2.8`` tag is the latest tag (``0.3.1``) is broken such that the node server constantly died. The same image above works perfectly fine on 4 other hosts except one that I'm having trouble(s) with. Any ideas?
