### ISSUE TITLE
Rails w/ mounted rack app looses session data

### ISSUE THREAD

**Issue by cpuguy83** [hipache/hipache#97]
I have a Rails app which is mounting a rack app to a route (Sidekiq::Web).
In my app the user must be signed in in order to view the Sidekiq GUI.

When using Hipache to route requests, I lose my session data and appear as signed out when I attempt to load the Sidekiq GUI.
Pulling Hipache out of the mix everything works ok.  It seems like something is getting mangled in the request.

**Comment by juanibiapina** [comment]
We have the exact same issue.
